apiVersion: v1
kind: Pod
metadata:
  labels:
    type: jenkins-agent
spec:
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/sh"
        - "-c"
        - "sleep 99d"
      tty: true
      securityContext:
        runAsUser: 0
    - name: hugo
      image: hugomods/hugo:exts
      imagePullPolicy: IfNotPresent
      command:
        - sleep
      args:
        - infinity
      workingDir: /home/jenkins/agent
      volumeMounts:
        - name: volumen-compartido
          mountPath: /web
  restartPolicy: Never
  volumes:
    - name: volumen-compartido
      persistentVolumeClaim:
        claimName: volumen-compartido
