apiVersion: v1
kind: Pod
metadata:
  name: ejemplo-pipeline-kubernetes
spec:
  containers:
    - name: web
      image: nginx:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      volumeMounts:
        - name: volumen-compartido
          mountPath: /usr/share/nginx/html
  volumes:
    - name: volumen-compartido
      persistentVolumeClaim:
        claimName: volumen-compartido
